// <auto-generated />
using System;
using Forshen.ERP.ProductManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forshen.ERP.ProductManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250716200453_Variants")]
    partial class Variants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forshen.ERP.ProductManagement.Entities.Dimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("Dimensions", (string)null);
                });

            modelBuilder.Entity("Forshen.ERP.ProductManagement.Entities.DimensionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DimensionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.ToTable("DimensionValues", (string)null);
                });

            modelBuilder.Entity("Forshen.ERP.ProductManagement.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Variants", (string)null);
                });

            modelBuilder.Entity("Forshen.ERP.ProductManagement.Entities.Dimension", b =>
                {
                    b.HasOne("Forshen.ERP.ProductManagement.Entities.Product", null)
                        .WithMany("Dimensions")
                        .HasForeignKey("ProductId");

                    b.HasOne("Forshen.ERP.ProductManagement.Entities.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId1");
                });

            modelBuilder.Entity("Forshen.ERP.ProductManagement.Entities.DimensionValue", b =>
                {
                    b.HasOne("Forshen.ERP.ProductManagement.Entities.Dimension", "Dimension")
                        .WithMany("DimensionValues")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimension");
                });

            modelBuilder.Entity("Forshen.ERP.ProductManagement.Entities.Dimension", b =>
                {
                    b.Navigation("DimensionValues");
                });

            modelBuilder.Entity("Forshen.ERP.ProductManagement.Entities.Product", b =>
                {
                    b.Navigation("Dimensions");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
